export const faqData = [
  {
    title: "About Us",
    text: "LorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejke",
  },

  {
    title: "Payment",
    text: "LorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejke",
  },

  {
    title: "BoNe token",
    text: "LorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejke",
  },

  {
    title: "Delivery",
    text: "LorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejke",
  },

  {
    title: "Discount",
    text: "LorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejke",
  },

  {
    title: "Web3",
    text: "LorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejke",
  },

  {
    title: "Ordering",
    text: "LorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejke",
  },

  {
    title: "Metamask",
    text: "LorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejkeLorasdjksdnhjdejkejkfjkenjrfejknrfnjjnfnjkerkjnfjnkerjknferjferjnfejknrfjnerjknfjknerjferjkfferjfjkerjkfjekrjfkerjfjejke",
  },
];
